---
title: |
  Will Moscato
description: 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Bio
My name is Will Moscato and I am a 2022 Macalester graduate with a degree in Applied Math and Statistics.
[Linkedin](https://www.linkedin.com/in/william-moscato-716708180/)
[Github](https://github.com/willmoscato?tab=repositories)


# Projects
## Predicting FIFA Team of the Season Players project
### This project used machine learning models to predict who would be in the "Team of the Season" for each league in the video game FIFA based upon real world statistics. [TOTS Predictor Website](https://totspredictor.netlify.app/).

## Pitch Predictor
### This project predicts what pitch was thrown in an MLB game based upon spin, velocity, and movement metrics. [Pitch Type Predictor Website](https://pitchpredictormachinelearning.netlify.app/).

## ERA Predictor
### This project takes swing data as well as some location data and attempts to predict a pitchers ERA. While this obviously does not work perfectly, it is very interesting to see which variables affect the ERA prediction the most. You can try it yourself on my [Shiny Website](https://wmoscato.shinyapps.io/ERAprediction/).